// <auto-generated />
using LI_Music.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LI_Music.Migrations;

[DbContext(typeof(LiMusicContext))]
[Migration("20260804134500_AprimorarLiMusic")]
public partial class AprimorarLiMusic : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<string>(
            name: "FotoUrl",
            table: "Artistas",
            type: "nvarchar(300)",
            maxLength: 300,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "Descricao",
            table: "Playlists",
            type: "nvarchar(300)",
            maxLength: 300,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "CapaUrl",
            table: "Musicas",
            type: "nvarchar(500)",
            maxLength: 500,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "Genero",
            table: "Musicas",
            type: "nvarchar(60)",
            maxLength: 60,
            nullable: true);

        migrationBuilder.AddColumn<int>(
            name: "UsuarioId",
            table: "Musicas",
            type: "int",
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "Login",
            table: "Usuarios",
            type: "nvarchar(40)",
            maxLength: 40,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "SenhaHash",
            table: "Usuarios",
            type: "nvarchar(64)",
            maxLength: 64,
            nullable: false,
            defaultValue: "");

        migrationBuilder.Sql("""
            DELETE pm
            FROM PlaylistMusicas pm
            INNER JOIN Musicas m ON m.Id = pm.MusicaId
            WHERE m.CaminhoArquivo LIKE '/musicas/n%.mp3';

            DELETE FROM Musicas
            WHERE CaminhoArquivo LIKE '/musicas/n%.mp3';

            DELETE FROM Playlists
            WHERE Nome IN ('Músicas da Isabela', 'Músicas da Lauany');

            DELETE FROM Artistas
            WHERE Nome IN ('Artista 1', 'Artista 2', 'Artista 3');

            UPDATE Usuarios
            SET Login = 'isabela',
                SenhaHash = 'f5644f9ae7564be5e6d3aa98abc3dd865b5e78119cc85c4e656f3884636a7a10'
            WHERE Id = 1 OR Nome = 'Isabela';

            UPDATE Usuarios
            SET Login = 'lauany',
                SenhaHash = '5a7ab7d7031693fcb5124073e2ad84734e3365bff91b140b1e4ff6b9bfaad8e4'
            WHERE Id = 2 OR Nome = 'Lauany';

            UPDATE Usuarios
            SET Login = LOWER(REPLACE(Nome, ' ', ''))
            WHERE Login = '';

            UPDATE Usuarios
            SET SenhaHash = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
            WHERE SenhaHash = '';

            UPDATE m
            SET UsuarioId = COALESCE(
                (
                    SELECT TOP 1 p.UsuarioId
                    FROM PlaylistMusicas pm
                    INNER JOIN Playlists p ON p.Id = pm.PlaylistId
                    WHERE pm.MusicaId = m.Id
                    ORDER BY p.Id
                ),
                (SELECT TOP 1 Id FROM Usuarios ORDER BY Id)
            )
            FROM Musicas m
            WHERE UsuarioId IS NULL;
            """);

        migrationBuilder.AlterColumn<int>(
            name: "UsuarioId",
            table: "Musicas",
            type: "int",
            nullable: false,
            oldClrType: typeof(int),
            oldType: "int",
            oldNullable: true);

        migrationBuilder.AlterColumn<string>(
            name: "Nome",
            table: "Usuarios",
            type: "nvarchar(80)",
            maxLength: 80,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(max)");

        migrationBuilder.AlterColumn<string>(
            name: "FotoUrl",
            table: "Usuarios",
            type: "nvarchar(300)",
            maxLength: 300,
            nullable: true,
            oldClrType: typeof(string),
            oldType: "nvarchar(max)",
            oldNullable: true);

        migrationBuilder.AlterColumn<string>(
            name: "Nome",
            table: "Artistas",
            type: "nvarchar(120)",
            maxLength: 120,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(max)");

        migrationBuilder.AlterColumn<string>(
            name: "Titulo",
            table: "Musicas",
            type: "nvarchar(150)",
            maxLength: 150,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(max)");

        migrationBuilder.AlterColumn<string>(
            name: "CaminhoArquivo",
            table: "Musicas",
            type: "nvarchar(500)",
            maxLength: 500,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(max)");

        migrationBuilder.AlterColumn<string>(
            name: "Nome",
            table: "Playlists",
            type: "nvarchar(100)",
            maxLength: 100,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(max)");

        migrationBuilder.CreateIndex(
            name: "IX_Usuarios_Login",
            table: "Usuarios",
            column: "Login",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_Musicas_CaminhoArquivo",
            table: "Musicas",
            column: "CaminhoArquivo",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_Musicas_UsuarioId",
            table: "Musicas",
            column: "UsuarioId");

        migrationBuilder.AddForeignKey(
            name: "FK_Musicas_Usuarios_UsuarioId",
            table: "Musicas",
            column: "UsuarioId",
            principalTable: "Usuarios",
            principalColumn: "Id",
            onDelete: ReferentialAction.NoAction);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "FK_Musicas_Usuarios_UsuarioId",
            table: "Musicas");

        migrationBuilder.DropIndex(
            name: "IX_Usuarios_Login",
            table: "Usuarios");

        migrationBuilder.DropIndex(
            name: "IX_Musicas_CaminhoArquivo",
            table: "Musicas");

        migrationBuilder.DropIndex(
            name: "IX_Musicas_UsuarioId",
            table: "Musicas");

        migrationBuilder.DropColumn(name: "FotoUrl", table: "Artistas");
        migrationBuilder.DropColumn(name: "Descricao", table: "Playlists");
        migrationBuilder.DropColumn(name: "CapaUrl", table: "Musicas");
        migrationBuilder.DropColumn(name: "Genero", table: "Musicas");
        migrationBuilder.DropColumn(name: "UsuarioId", table: "Musicas");
        migrationBuilder.DropColumn(name: "Login", table: "Usuarios");
        migrationBuilder.DropColumn(name: "SenhaHash", table: "Usuarios");

        migrationBuilder.AlterColumn<string>(
            name: "Nome",
            table: "Usuarios",
            type: "nvarchar(max)",
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(80)",
            oldMaxLength: 80);

        migrationBuilder.AlterColumn<string>(
            name: "FotoUrl",
            table: "Usuarios",
            type: "nvarchar(max)",
            nullable: true,
            oldClrType: typeof(string),
            oldType: "nvarchar(300)",
            oldMaxLength: 300,
            oldNullable: true);

        migrationBuilder.AlterColumn<string>(
            name: "Nome",
            table: "Artistas",
            type: "nvarchar(max)",
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(120)",
            oldMaxLength: 120);

        migrationBuilder.AlterColumn<string>(
            name: "Titulo",
            table: "Musicas",
            type: "nvarchar(max)",
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(150)",
            oldMaxLength: 150);

        migrationBuilder.AlterColumn<string>(
            name: "CaminhoArquivo",
            table: "Musicas",
            type: "nvarchar(max)",
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(500)",
            oldMaxLength: 500);

        migrationBuilder.AlterColumn<string>(
            name: "Nome",
            table: "Playlists",
            type: "nvarchar(max)",
            nullable: false,
            oldClrType: typeof(string),
            oldType: "nvarchar(100)",
            oldMaxLength: 100);
    }
}