// <auto-generated />
using LI_Music.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LI_Music.Migrations;

[DbContext(typeof(LiMusicContext))]
partial class LiMusicContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.29")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("LI_Music.Models.Artista", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("FotoUrl")
                .HasMaxLength(300)
                .HasColumnType("nvarchar(300)");

            b.Property<string>("Nome")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("nvarchar(120)");

            b.HasKey("Id");
            b.ToTable("Artistas");
        });

        modelBuilder.Entity("LI_Music.Models.Usuario", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("FotoUrl")
                .HasMaxLength(300)
                .HasColumnType("nvarchar(300)");

            b.Property<string>("Login")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("nvarchar(40)");

            b.Property<string>("Nome")
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnType("nvarchar(80)");

            b.Property<string>("SenhaHash")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.HasKey("Id");
            b.HasIndex("Login").IsUnique();
            b.ToTable("Usuarios");
        });

        modelBuilder.Entity("LI_Music.Models.Musica", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<int>("ArtistaId").HasColumnType("int");

            b.Property<string>("CaminhoArquivo")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("CapaUrl")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<int>("DuracaoSegundos").HasColumnType("int");

            b.Property<string>("Genero")
                .HasMaxLength(60)
                .HasColumnType("nvarchar(60)");

            b.Property<string>("Titulo")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("nvarchar(150)");

            b.Property<int>("UsuarioId").HasColumnType("int");

            b.HasKey("Id");
            b.HasIndex("ArtistaId");
            b.HasIndex("CaminhoArquivo").IsUnique();
            b.HasIndex("UsuarioId");
            b.ToTable("Musicas");
        });

        modelBuilder.Entity("LI_Music.Models.Playlist", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Descricao")
                .HasMaxLength(300)
                .HasColumnType("nvarchar(300)");

            b.Property<string>("Nome")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<int>("UsuarioId").HasColumnType("int");

            b.HasKey("Id");
            b.HasIndex("UsuarioId");
            b.ToTable("Playlists");
        });

        modelBuilder.Entity("LI_Music.Models.PlaylistMusica", b =>
        {
            b.Property<int>("PlaylistId").HasColumnType("int");
            b.Property<int>("MusicaId").HasColumnType("int");

            b.HasKey("PlaylistId", "MusicaId");
            b.HasIndex("MusicaId");
            b.ToTable("PlaylistMusicas");
        });

        modelBuilder.Entity("LI_Music.Models.Musica", b =>
        {
            b.HasOne("LI_Music.Models.Artista", "Artista")
                .WithMany("Musicas")
                .HasForeignKey("ArtistaId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("LI_Music.Models.Usuario", "Usuario")
                .WithMany("Musicas")
                .HasForeignKey("UsuarioId")
                .OnDelete(DeleteBehavior.NoAction)
                .IsRequired();

            b.Navigation("Artista");
            b.Navigation("Usuario");
        });

        modelBuilder.Entity("LI_Music.Models.Playlist", b =>
        {
            b.HasOne("LI_Music.Models.Usuario", "Usuario")
                .WithMany("Playlists")
                .HasForeignKey("UsuarioId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Usuario");
        });

        modelBuilder.Entity("LI_Music.Models.PlaylistMusica", b =>
        {
            b.HasOne("LI_Music.Models.Musica", "Musica")
                .WithMany("PlaylistMusicas")
                .HasForeignKey("MusicaId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("LI_Music.Models.Playlist", "Playlist")
                .WithMany("PlaylistMusicas")
                .HasForeignKey("PlaylistId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Musica");
            b.Navigation("Playlist");
        });

        modelBuilder.Entity("LI_Music.Models.Artista", b => b.Navigation("Musicas"));
        modelBuilder.Entity("LI_Music.Models.Musica", b => b.Navigation("PlaylistMusicas"));
        modelBuilder.Entity("LI_Music.Models.Playlist", b => b.Navigation("PlaylistMusicas"));
        modelBuilder.Entity("LI_Music.Models.Usuario", b =>
        {
            b.Navigation("Musicas");
            b.Navigation("Playlists");
        });
#pragma warning restore 612, 618
    }
}